### ISSUE TITLE
feature request: support windows

### ISSUE THREAD

**Issue by steambap** [Rokid/node-webworker#5]
fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

**Comment by lujnan** [comment]
@steambap @yorkie   you can try this 
```
#if defined( _WIN64) || defined(_WIN32)
#include <io.h>
#else
#include <unistd.h>
#endif
```

**Comment by steambap** [comment]
I got another error when I use io.h instead of unistd.h:

```
LINK : fatal error LNK1181: cannot open input file 'pthread.lib'
```

**Comment by yorkie** [comment]
This library does depend on the POSIX/GNU library pthread which not portable on Windows, so this library cannot work on your machine.

**Comment by yorkie** [comment]
By the way, @steambap would you please edit the title to be like "feature request: support windows"?
