### ISSUE TITLE
how to call defines functions in worker

### ISSUE THREAD

**Issue by rajeshtomjoe** [Rokid/node-webworker#8]
i am trying to call a function inside worker using defines option. i would like to use request as require in worker is not supported.

any example would help?

**Comment by yorkie** [comment]
> i would like to use request as require in worker is not supported.

Exactly, currently the `require` function in worker is used to load non-third-party modules. And this is an example for you:

```js
const request = require('request');
const worker = new WebWorker(function(self, request) {
  request('http://foobar', function(err, res) {
    // something
  });
}, defines: [
  function (url, cb) {
    request(url, function(err, data) {
      cb(err, data);
    });
  }
]);
```

**Comment by rajeshtomjoe** [comment]
Hi thanks for snippet it works perfectly. I am having one more problem related with using Buffer in worker

i am getting

```
#
# Fatal error in v8::ToLocalChecked
# Empty MaybeLocal.
#

Illegal instruction (core dumped)
```

when using Buffer.from("ffff","hex");

**Comment by yorkie** [comment]
Yea, `Buffer` in worker still not working well, could you please encapsulate the buffer operations into a function and expose via `defines` options, too?

**Comment by rajeshtomjoe** [comment]
Ya that serves the purpose for now. Thanks yorkie.

**Comment by yorkie** [comment]
:)
